<?php
/*
        Question2Answer by Gideon Greenspan and contributors
        http://www.question2answer.org/

        File: qa-lang/de/qa-lang-admin.php
        Version: 1.8
        Date: 2019-09-29
        Description: Language phrases for admin center in formal German (Sie)
        Translation: Fulgor@github

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
	'active_widgets_explanation' => 'Derzeit aktivierte Widgets:',
	'add_category_button' => 'Kategorie hinzufügen',
	'add_field_button' => 'Feld hinzufügen',
	'add_link_button' => 'Link  hinzufügen',
	'add_link_link' => ' - ^1Link hinzufügen^2',
	'add_new_field' => 'Neues Feld hinzufügen',
	'add_new_title' => 'Neuen Titel hinzufügen',
	'add_page_button' => 'Seite hinzufügen',
	'add_title_button' => 'Titel hinzufügen',
	'add_widget_button' => 'Widget hinzufügen',
	'add_widget_link' => ' - ^1Widget hinzufügen^2',
	'admin_title' => 'Administration',
	'after_footer' => 'Nach Links im Fussbereich',
	'after_main_menu' => 'Nach den oberen Tabs',
	'after_x' => 'Nach "^"',
	'after_x_tab' => 'Nach "^" Tab',
	'approve_user_popup' => 'Bestätige Nutzer',
	'approve_users_title' => 'Bestätige Nutzer',
	'basic_editor' => 'Basis Editor',
	'before_main_menu' => 'Vor den oberen Tabs',
	'blobs_directory_error' => 'Für das als QA_BLOBS_DIRECTORY festgelegte Verzeichnis ^ fehlen die Schreibrechte auf dem Server.',
	'blobs_move_complete' => 'Übertragung der hochgeladenen Bilder und Dokumente ageschlossen.',
	'blobs_move_moved' => 'Übertrage ^1 von ^2 der hochgeladenen Bilder und Dokumente',
	'blobs_stop' => 'Übertragung angehalten',
	'blobs_to_db' => 'Blobs zur Datenbank',
	'blobs_to_db_note' => '- übertrage alle hochgeladenen Bilder und Dokumente zur Datenbank',
	'blobs_to_disk' => 'Blobs zur Festplatte',
	'blobs_to_disk_note' => '- übertrage alle hochgeladenen Bilder und Dokumente von der Datenbank zur Festplatte',
	'block_button' => 'block',
	'block_ips_note' => 'Nutzen Sie "-" für Bereiche oder "*" als Variable für jede Zahl. Beispiele: 192.168.0.4 , 192.168.0.0-192.168.0.31 , 192.168.0.*',
	'block_user_popup' => 'Block Nutzer',
	'block_words_note' => 'Nutzen Sie "*" für jeden Buchstaben. Beispiele: doh (passt nur auf "doh") , doh* (passt auf "doh" oder "dohno") , do*h (passt auf "doh", "dooh", "dough").',
	'caching_cleanup' => 'Aufräumen des Caches',
	'caching_delete_all' => 'Ganzen Cache löschen',
	'caching_delete_complete' => 'Cache erfolgreich gelöscht',
	'caching_delete_expired' => 'Lösche abgelaufenen Cache',
	'caching_delete_progress' => '^1 von ^2 Cache-Dateien gelöscht...',
	'caching_dir_error' => 'Für das als QA_CACHE_DIRECTORY festgelegte Verzeichnis ^ fehlen die Schreibrechte auf dem Server.',
	'caching_dir_missing' => 'Cache-Verzeichnis wurde nicht festgelegt.',
	'caching_dir_public' => 'Das als QA_CACHE_DIRECTORY festgelegte Verzeichnis ^ muss sich ausserhalb des öffentlichen Wurzelverzeichnisses befinden.',
	'caching_num_items' => 'Anzahl der Elemente im Cache',
	'caching_space_used' => 'Gesamtgröße des Cache',
	'caching_title' => 'Cache',
	'cancel_mailing_button' => 'E-Mail-Versand abbrechen',
	'categories' => 'Kategorien',
	'categories_introduction' => 'Klicken Sie auf \'Kategorie hinzufügen\', um mit Kategorien zu beginnen.',
	'categories_not_shown' => 'Einige Fragen haben Kategorien, die nicht angezeigt werden.',
	'categories_title' => 'Kategorien',
	'category_add_sub' => 'Unter-Kategorie hinzufügen',
	'category_added' => 'Kategorie hinzugefügt',
	'category_already_used' => 'Das wird bereits von einer Kategorie verwendet.',
	'category_default_slug' => 'Kategorie-^',
	'category_description' => 'Optionale Beschreibung der Kategorie:',
	'category_max_depth_x' => 'Manche Optionen können versteckt sein, um zu verhindern, dass eine Kategorie tiefer als Ebene ^ liegt.',
	'category_move_parent' => 'verschiebe zu einem anderen Eltern-Element',
	'category_name' => 'Name der Kategorie:',
	'category_name_first' => 'Name der ersten Kategorie:',
	'category_no_add_subs_x' => 'Diese Kategorie kann keine Unterkategorien haben, denn sie ist bereits auf Ebene ^.',
	'category_no_delete_subs' => 'Diese Kategorie kann nicht gelöscht werden, da sie eine Unterkategorie hat.',
	'category_no_sub_error' => '^q Frage/n in dieser Kategorie haben keine Unterkategorie - ^1Unterkategorie festlegen^2',
	'category_no_sub_to' => 'Verschiebe Fragen in ^ ohne Unterkategorie nach:',
	'category_no_subs' => 'Keine',
	'category_none_error' => '^q Frage/n haben noch keine Kategorie - ^1Kategorie festlegen^2',
	'category_none_to' => 'Verschiebe Fragen ohne Kategorie nach:',
	'category_parent' => 'Elternkategorie:',
	'category_saved' => 'Kategorie gespeichert',
	'category_slug' => 'Kategorie Kurzform - URL Fragment:',
	'category_subs' => 'Unterkategorien:',
	'category_top_level' => 'Keine Elternkategorie (oberste Ebene)',
	'characters' => 'Buchstaben',
	'check_language_suffix' => ' - ^1prüfe Sprachdateien^2',
	'click_name_edit' => 'Eigene Seiten oder Links:',
	'database_cleanup' => 'Funktionen um Datenbank zu bereinigen',
	'delete_category' => 'Diese Kategorie löschen',
	'delete_category_reassign' => 'Diese Kategorie löschen und ihre Fragen zuordnen an:',
	'delete_field' => 'Dieses Feld löschen',
	'delete_hidden' => 'Versteckte Einträge löschen',
	'delete_hidden_complete' => 'Alle versteckten Einträge ohne Abhängigkeiten wurden gelöscht',
	'delete_hidden_note' => ' - alle versteckten Einträge, Antworten und Kommentare ohne Abhängigkeiten',
	'delete_link' => 'Diesen Link löschen',
	'delete_page' => 'Diese Seite löschen',
	'delete_stop' => 'Löschen abbrechen',
	'delete_title' => 'Diesen Titel löschen',
	'delete_widget_position' => 'Dieses Widget von dieser Position löschen',
	'edit_custom_page' => 'Eigene Seite bearbeiten',
	'edit_field' => ' - ^1Feld bearbeiten^2',
	'edit_link' => ' - ^1Link bearbeiten^2',
	'edit_page' => ' - ^1Seite bearbeiten^2',
	'edit_title' => ' - ^1Titel bearbeiten^2',
	'emails_per_minute' => 'E-Mails pro Minute',
	'emails_title' => 'E-Mails',
	'enabled' => 'Freigegeben',
	'feed_link' => 'Feed',
	'feed_link_example' => 'Beispiel-Feed',
	'feeds_title' => 'RSS-Feeds',
	'field_link_url' => 'Verlinkte URL',
	'field_multi_line' => 'Mehrere Zeilen Text',
	'field_name' => 'Feldname:',
	'field_single_line' => 'Einzelne Textzeile',
	'field_type' => 'Inhaltstyp:',
	'first' => 'Erster',
	'flagged_title' => 'Flagged',
	'form_security_expired' => 'Sicherheitscode des Formulars abgelaufen - bitte erneut versuchen',
	'from_anon' => 'Von Anonymous:',
	'from_users' => 'Von Nutzenden:',
	'general_title' => 'Allgemein',
	'hidden_answers_deleted' => 'Gelöscht: ^1 von ^2 versteckten Antworten ohne Abhängigkeiten ...',
	'hidden_comments_deleted' => 'Gelöscht: ^1 von ^2 versteckt Kommentare ...',
	'hidden_questions_deleted' => 'Gelöscht: ^1 von ^2 versteckte Fragen ohne Abhängigkeiten ...',
	'hidden_title' => 'Versteckt',
	'hotness_factors' => 'Relative Bedeutung für Aktualität der Frage:',
	'ip_address_pages' => 'IP Adressseiten',
	'layout_title' => 'Layout',
	'link_name' => 'Text des Links:',
	'link_new_window' => 'Öffne Link in einem neuen Fenster',
	'link_url' => 'URL des Links - absolut oder relativ zum Q2A Wurzelverzeichnis:',
	'lists_title' => 'Listen',
	'mailing_complete' => 'Der Mail-Versand ist abgeschlossen',
	'mailing_explanation' => 'Nutzende können Abo auf ihrer Kontoseite beenden.',
	'mailing_progress' => 'Mail-Versand für ^1 von ^2 Nutzende abgeschlossen ...',
	'mailing_title' => 'Mail-Versand',
	'mailing_unsubscribe' => 'Am Ende jeder Nachricht wird ein Link eingefügt, um das Abo zu beenden.',
	'maintenance_admin_only' => 'Ihre Website ist im ^1Wartungsmodus^2 und derzeit für normale Nutzende nicht zugänglich.',
	'maximum_x' => ' (maximal ^)',
	'memcached_error' => 'Memcached Fehler: ^',
	'moderate_title' => 'Moderieren',
	'module_x_database_init' => 'Das ^1 ^2 Modul benötigt eine ^3Initialisierung der Datenbank^4.',
	'most_flagged_title' => 'Markierter Inhalt',
	'mysql_version' => 'MySQL Version:',
	'nav_links_explanation' => 'Zeige Navigationslinks:',
	'nav_qa_is_home' => 'Q&A (Links zur Startseite)',
	'neat_urls_note' => ' (benötigt ^1htaccess^2 Datei)',
	'no_approve_found' => 'Keine Inhalte, die auf Freigabe warten',
	'no_classification' => 'Keine',
	'no_flagged_found' => 'Kein markierter Inhalt gefunden',
	'no_hidden_found' => 'Kein versteckter Inhalt gefunden',
	'no_image_gd' => 'Das installierte PHP wurde ohne die "GD library" kompiliert. Nutzende können ihre Avatare daher nicht direkt hochladen.',
	'no_link' => 'Kein Link',
	'no_memcached' => 'Die PHP Erweiterung Memcached ist nicht installiert.',
	'no_multibyte' => 'Das installierte PHP wurde ohne wurde ohne Unterstützung für Multibyte Strings kompiliert. Die Suche ist daher für nicht-Lateinische Buchstaben weniger effektiv.',
	'no_privileges' => 'Zugriff auf diese Seite nur mit administrativen Rechten.',
	'no_unapproved_found' => 'Keine Nutzenden warten auf Bestätigung',
	'not_logged_in' => 'Bitte mit administrativen Rechten ^1anmelden^2, um die Seite aufzurufen.',
	'opposite_main_menu' => 'Entferntes Ende der Tabs oben',
	'options' => 'Optionen',
	'options_reset' => 'Optionen zurück gesetzt',
	'options_saved' => 'Optionen gesichert',
	'page_already_used' => 'Das wird bereits von von einer Seite genutzt',
	'page_content_html' => 'Inhalt der auf der Seite angezeigt werden soll - HTML erlaubt:',
	'page_default_slug' => 'Seite-^',
	'page_heading' => 'Überschrift die oben auf der Seite angezeigt werden soll:',
	'page_name' => 'Name der Seite (auch für Tab und Link):',
	'page_slug' => 'Seitenkürzel (URL-Fragment):',
	'pages_explanation' => 'Wählen Sie \'Seite hinzufügen\' um eigene Inhalte Ihrer Q2A Website hinzuzufügen, oder \'Link hinzufügen\' um auf eine andere Seite zu verlinken.',
	'pages_title' => 'Seiten',
	'pause_mailing_button' => 'E-Mail-Versand unterbrechen',
	'per_ip_hour' => 'pro IP/Stunde',
	'per_user_hour' => 'pro Nutzer/Stunde',
	'permissions_title' => 'Berechtigungen',
	'permit_to_view' => 'Sichtbar für:',
	'php_version' => 'PHP Version:',
	'pixels' => 'Pixel',
	'plugin_module' => ' (Erweiterungen: ^)',
	'plugin_pages_explanation' => 'Seiten verfügbar über Erweiterungen:',
	'plugins_title' => 'Erweiterungen',
	'points' => 'Punkte',
	'points_defaults_shown' => 'Standards die unten gezeigt aber NOCH NICHT ANGEWANDT werden:',
	'points_required' => 'Mindestpunktzahl um Titel zu erhalten:',
	'points_title' => 'Punkte',
	'position' => 'Position:',
	'posting_title' => 'Eintrag',
	'profile_fields' => 'Extrafelder auf Nutzerseiten oder dem Formular zur Registrierung:',
	'q2a_build_date' => 'Build date:',
	'q2a_db_size' => 'Datenbankgröße:',
	'q2a_db_version' => 'Q2A Datenbankversion:',
	'q2a_latest_version' => 'Letzte Version:',
	'q2a_version' => 'Question2Answer Version:',
	'question_lists' => 'Fragenlisten',
	'question_pages' => 'Fragenseiten',
	'recalc_categories' => 'Kategorien neu berechnen',
	'recalc_categories_backpaths' => 'URL-Pfade für Kategorie ^1 von ^2 neu berechnen...',
	'recalc_categories_complete' => 'Alle Kategorie wurden erfolgreich neu berechnet.',
	'recalc_categories_note' => ' - für Eintragskategorie und Kategoriezähler',
	'recalc_categories_recounting' => 'Neuberechnung der Fragen aus Kategorie ^1 von ^2 ...',
	'recalc_categories_updated' => 'Neuberechnung der Einträge ^1 von ^2 ...',
	'recalc_hotness_q_view_note' => 'Kann Seitenaufbau etwas schneller machen, wenn ausgeschaltet. Allerdings werden die Hotness-Werte nicht aktuell sein, wenn die Aufrufe in den Hotness-Einstellungen berücksichtigt werden.',
	'recalc_points' => 'Neuberechnung der Punktwerte der Nutzenden',
	'recalc_points_complete' => 'Punktwerte der Nutzenden wurden erfolgreich neu berechnet.',
	'recalc_points_note' => ' - für die Darstellung von Rang und Punkten der Nutzenden',
	'recalc_points_recalced' => 'Neuberechnung für Nutzenden ^1 von ^2 ...',
	'recalc_points_usercount' => 'Schätze Gesamtzahl der Nutzenden ...',
	'recalc_posts_count' => 'Getting total number of questions, answers and comments...',
	'recalc_stop' => 'Stop recalculating',
	'recent_approve_title' => 'Recent content waiting for approval',
	'recent_hidden_title' => 'Recent hidden content',
	'recount_posts' => 'Recount posts',
	'recount_posts_as_recounted' => 'Recounted answers and hotness for ^1 of ^2 posts...',
	'recount_posts_complete' => 'All posts were successfully recounted.',
	'recount_posts_note' => ' - the number of answers, votes, flags and hotness for each post',
	'recount_posts_stop' => 'Stop recounting',
	'recount_posts_votes_recounted' => 'Recounted votes and flags for ^1 of ^2 posts...',
	'refill_events' => 'Refill event streams',
	'refill_events_complete' => 'All events streams were successfully refilled',
	'refill_events_note' => ' - for each user\'s list of updates',
	'refill_events_refilled' => 'Refilled for ^1 of ^2 questions...',
	'registration_fields' => 'add registration fields',
	'reindex_content' => 'Reindex content',
	'reindex_content_note' => ' - for searching and related question suggestions',
	'reindex_content_stop' => 'Stop reindexing',
	'reindex_pages_reindexed' => 'Reindexed ^1 of ^2 pages...',
	'reindex_posts_complete' => 'All posts were successfully reindexed.',
	'reindex_posts_reindexed' => 'Reindexed ^1 of ^2 posts...',
	'reindex_posts_wordcounted' => 'Recounted ^1 of ^2 words...',
	'requires_php_version' => 'Disabled - requires PHP ^ or later',
	'requires_q2a_version' => 'Disabled - requires Question2Answer ^ or later',
	'reset_options_button' => 'Reset to Defaults',
	'reset_options_confirm' => 'Are you sure you want to reset all options on this page to their defaults?',
	'resume_mailing_button' => 'Resume Mailing',
	'save_options_button' => 'Save Options',
	'save_recalc_button' => 'Save and Recalculate',
	'save_view_button' => 'Save and View',
	'send_test_button' => 'Send Test to Me',
	'show_defaults_button' => 'Show Defaults',
	'show_on_register_form' => 'Show field on user registration form',
	'slug_bad_chars' => 'The slug may not contain these characters: ^',
	'slug_reserved' => 'This slug is reserved for use by another page',
	'spam_title' => 'Spam',
	'start_mailing_button' => 'Start Mailing',
	'stats_title' => 'Stats',
	'stop_recalc_warning' => 'A database clean-up operation is running. If you close this page now, the operation will be interrupted.',
	'tag_pages' => 'Tag pages',
	'tags' => 'Tags',
	'tags_and_categories' => 'Tags and Categories',
	'tags_not_shown' => 'Some questions have tags which will not be displayed.',
	'test_sent_to_x' => 'The test message was sent to ^',
	'title_already_used' => 'This value is already being used by another title',
	'top_level_categories' => 'Top level categories:',
	'total_as' => 'Total answers:',
	'total_cs' => 'Total comments:',
	'total_qs' => 'Total questions:',
	'total_qs_unans' => 'Total questions unanswered:',
	'unnamed_plugin' => 'Unnamed Plugin',
	'upgrade_db' => 'Your Question2Answer database needs to be ^1upgraded^2 for this version.',
	'url_format_note' => 'Options with the ^ label are working for your site\'s configuration. For best search engine optimization (SEO), use the first ^ option available.',
	'user_pages' => 'User pages',
	'user_title' => 'User title - HTML allowed:',
	'user_titles' => 'User titles based on points:',
	'users_active' => 'Active users:',
	'users_must_have' => 'Users must have',
	'users_posted' => 'Users who posted:',
	'users_registered' => 'Registered users:',
	'users_title' => 'Users',
	'users_voted' => 'Users who voted:',
	'version_get_x' => 'get ^',
	'version_latest' => 'latest',
	'version_latest_unknown' => 'latest unknown',
	'version_requires_php' => '^1 requires PHP ^2',
	'version_requires_q2a' => '^1 requires Q2A ^2',
	'viewing_title' => 'Viewing',
	'widget_all_pages' => 'Show widget in this position on all available pages',
	'widget_global_options' => ' - ^1options^2',
	'widget_name' => 'Name of widget:',
	'widget_no_positions' => 'This widget has already been added to every available position.',
	'widget_not_available' => 'This widget is not available. This could be because the plugin providing the widget is no longer installed.',
	'widget_pages_explanation' => 'Show widget in this position on the following pages:',
	'widgets_explanation' => 'Available widgets:',
);

/*
 	 Omit PHP closing tag to help avoid accidental output
*/
